### ISSUE TITLE
Crash when song is missing year metadata

### ISSUE THREAD

**Issue by skmd0** [glomatico/gytmdl#1]
It seems like some songs could be missing `year` metadata and when that happens script crashes. [Example song](https://youtube.com/watch?v=cM0FEGDwfRg) from trace below. This is not a sole example, the same issue occurred for 3 other songs.

```python
Failed to download "Syntax" (track 194/194) from URL 1/1)
Traceback (most recent call last):
  File "C:\Users\redacted\AppData\Roaming\Python\Python310\site-packages\gytmdl\__init__.py", line 111, in main
    tags = dl.get_tags(ytmusic_watch_playlist)
  File "C:\Users\redacted\AppData\Roaming\Python\Python310\site-packages\gytmdl\gytmdl.py", line 85, in get_tags
    '\xa9day': [ytmusic_album['year']],
KeyError: 'year'
```

**Comment by glomatico** [comment]
Should be fixed in the new version.
