### ISSUE TITLE
Fails to download

### ISSUE THREAD

**Issue by MrAlaux** [glomatico/gytmdl#23]
As the title says.

The last time it worked successfully was on the 5th of June. Just moments ago I tried to use it again and got this:

<details><summary>Details</summary>
<p>

```
>gytmdl "[url]"

[INFO     03:30:57] (URL 1/1) Checking "[url]"
[INFO     03:31:02] (Track 1/1 from URL 1/1) Downloading "[track]"
[ERROR    03:31:03] (Track 1/1 from URL 1/1) Failed to download "[track]"
Traceback (most recent call last):
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\lib\site-packages\gytmdl\cli.py", line 300, in main
    tags = downloader.get_tags(ytmusic_watch_playlist)
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\lib\site-packages\gytmdl\downloader.py", line 199, in get_tags
    ytmusic_album = self.get_ytmusic_album(
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\lib\site-packages\gytmdl\downloader.py", line 191, in get_ytmusic_album
    return self.ytmusic.get_album(browse_id)
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\lib\site-packages\ytmusicapi\mixins\browsing.py", line 412, in get_album
    album = parse_album_header(response)
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\lib\site-packages\ytmusicapi\parsers\albums.py", line 7, in parse_album_header
    header = nav(response, HEADER_DETAIL)
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\lib\site-packages\ytmusicapi\navigation.py", line 81, in nav
    raise err
  File "C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\lib\site-packages\ytmusicapi\navigation.py", line 75, in nav
    root = root[k]
KeyError: 'header'
[INFO     03:31:03] Done (1 error(s))
```

</p>
</details> 

I was using version 1.6, but I updated to and tried using 2.0 (from which I got the log above), to no avail. FWIW, I didn't update Python since the last time it worked.

**Comment by glomatico** [comment]
Which URL did you tried?

**Comment by MrAlaux** [comment]
Here's one that worked previously, but not anymore:
https://www.youtube.com/playlist?list=OLAK5uy_k0PMx-H9YMTznLRPk5pijLRUv3bOJNkgc

**Comment by MrAlaux** [comment]
Sorry to bother, but it's unclear to me why you closed this. What's your conclusion?

**Comment by glomatico** [comment]
I can't reproduce this issue.

**Comment by MrAlaux** [comment]
Looks like I managed to solve it.

After updating `ytmusicapi`, I got a different error, which made me realize that I was using my gytmdl-1.6 folder template with gytmdl-2.0, which didn't work because dates are handled differently. I fixed that and the app is mostly functional now.
