### ISSUE TITLE
Tracks are not downloading!

### ISSUE THREAD

**Issue by allpeoplen00bs** [glomatico/gytmdl#24]
```
[DEBUG    22:55:19] Starting downloader
[INFO     22:55:20] (URL 1/1) Checking "https://music.youtube.com/playlist?list=OLAK5uy_ncXuoX17aD34URnJTuNU3_kEn5u8p-R9o"
[INFO     22:55:21] (Track 1/2 from URL 1/1) Downloading "Searching"
[DEBUG    22:55:21] Getting tags
[ERROR    22:55:23] (Track 1/2 from URL 1/1) Failed to download "Searching"
[INFO     22:55:23] (Track 2/2 from URL 1/1) Downloading "Paradox"
[DEBUG    22:55:23] Getting tags
[ERROR    22:55:24] (Track 2/2 from URL 1/1) Failed to download "Paradox"
[INFO     22:55:24] Done (2 error(s))
```

**Comment by glomatico** [comment]
Run the command again but with `--print-exceptions` at the end.

**Comment by allpeoplen00bs** [comment]
```
[DEBUG    00:57:40] Starting downloader
[INFO     00:57:40] (URL 1/1) Checking "https://music.youtube.com/playlist?list=OLAK5uy_ncXuoX17aD34URnJTuNU3_kEn5u8p-R9o"
[INFO     00:57:41] (Track 1/2 from URL 1/1) Downloading "Searching"
[DEBUG    00:57:41] Getting tags
[ERROR    00:57:44] (Track 1/2 from URL 1/1) Failed to download "Searching"
Traceback (most recent call last):
  File "C:\Users\haker\AppData\Local\Programs\Python\Python312\Lib\site-packages\ytmusicapi\navigation.py", line 106, in nav
    root = root[k]
           ~~~~^^^
KeyError: 'navigationEndpoint'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\haker\AppData\Local\Programs\Python\Python312\Lib\site-packages\gytmdl\cli.py", line 300, in main
    tags = downloader.get_tags(ytmusic_watch_playlist)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\haker\AppData\Local\Programs\Python\Python312\Lib\site-packages\gytmdl\downloader.py", line 199, in get_tags
    ytmusic_album = self.get_ytmusic_album(
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\haker\AppData\Local\Programs\Python\Python312\Lib\site-packages\gytmdl\downloader.py", line 191, in get_ytmusic_album
    return self.ytmusic.get_album(browse_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\haker\AppData\Local\Programs\Python\Python312\Lib\site-packages\ytmusicapi\mixins\browsing.py", line 521, in get_album
    album = parse_album_header_2024(response)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\haker\AppData\Local\Programs\Python\Python312\Lib\site-packages\ytmusicapi\parsers\albums.py", line 54, in parse_album_header_2024
    album_info["artists"] = [parse_base_header(header)["author"]]
                             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\haker\AppData\Local\Programs\Python\Python312\Lib\site-packages\ytmusicapi\parsers\podcasts.py", line 67, in parse_base_header
    "id": nav(strapline, ["runs", 0, *NAVIGATION_BROWSE_ID]),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\haker\AppData\Local\Programs\Python\Python312\Lib\site-packages\ytmusicapi\navigation.py", line 110, in nav
    raise type(e)(f"Unable to find '{k}' using path {items!r} on {root!r}, exception: {e}")
KeyError: "Unable to find 'navigationEndpoint' using path ['runs', 0, 'navigationEndpoint', 'browseEndpoint', 'browseId'] on {'text': 'James iD'}, exception: 'navigationEndpoint'"
[INFO     00:57:44] (Track 2/2 from URL 1/1) Downloading "Paradox"
[DEBUG    00:57:44] Getting tags
[ERROR    00:57:44] (Track 2/2 from URL 1/1) Failed to download "Paradox"
Traceback (most recent call last):
  File "C:\Users\haker\AppData\Local\Programs\Python\Python312\Lib\site-packages\ytmusicapi\navigation.py", line 106, in nav
    root = root[k]
           ~~~~^^^
KeyError: 'navigationEndpoint'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\haker\AppData\Local\Programs\Python\Python312\Lib\site-packages\gytmdl\cli.py", line 300, in main
    tags = downloader.get_tags(ytmusic_watch_playlist)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\haker\AppData\Local\Programs\Python\Python312\Lib\site-packages\gytmdl\downloader.py", line 199, in get_tags
    ytmusic_album = self.get_ytmusic_album(
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\haker\AppData\Local\Programs\Python\Python312\Lib\site-packages\gytmdl\downloader.py", line 191, in get_ytmusic_album
    return self.ytmusic.get_album(browse_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\haker\AppData\Local\Programs\Python\Python312\Lib\site-packages\ytmusicapi\mixins\browsing.py", line 521, in get_album
    album = parse_album_header_2024(response)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\haker\AppData\Local\Programs\Python\Python312\Lib\site-packages\ytmusicapi\parsers\albums.py", line 54, in parse_album_header_2024
    album_info["artists"] = [parse_base_header(header)["author"]]
                             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\haker\AppData\Local\Programs\Python\Python312\Lib\site-packages\ytmusicapi\parsers\podcasts.py", line 67, in parse_base_header
    "id": nav(strapline, ["runs", 0, *NAVIGATION_BROWSE_ID]),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\haker\AppData\Local\Programs\Python\Python312\Lib\site-packages\ytmusicapi\navigation.py", line 110, in nav
    raise type(e)(f"Unable to find '{k}' using path {items!r} on {root!r}, exception: {e}")
KeyError: "Unable to find 'navigationEndpoint' using path ['runs', 0, 'navigationEndpoint', 'browseEndpoint', 'browseId'] on {'text': 'James iD'}, exception: 'navigationEndpoint'"
[INFO     00:57:44] Done (2 error(s))
```

**Comment by glomatico** [comment]
Can't do anything about it, sorry.
